### ISSUE TITLE
[1.16] Multiple Fusion Crafting Core nearby interfere with each other

### ISSUE THREAD

**Issue by StellaSmith** [Draconic-Inc/Draconic-Evolution#1668]
## Base information
* Minecraft version: 1.16.5
* Mod version: Draconic-Evolution-1.16.5-3.0.25.456-universal.jar
* Minecraft Forge version: 36.2.34
* Mod Pack: All the Mods 6

### Description / steps to reproduce
I tried automating the recipes for injectors so i build two setups close to each other to save on space.
After building and trying out the second one, and after trying to start it, it stopped immediately.

I'm using RFTools' timer to automatically start the process and Refined Storage for the rest.
Here's a video showing of this behavior and my setup.
https://cdn.discordapp.com/attachments/915691398852915210/990716286084481085/2022-06-26_16-30-54.mp4

**Comment by FoxMcloud5655** [comment]
That's really weird, but it should only happen if there's Redstone signals interfering with the crafting process.  Can you test this setup without your automation?

**Comment by StellaSmith** [comment]
Looks like when the first infuser gets a redstone signal the second one stops.
https://cdn.discordapp.com/attachments/915691398852915210/990762512477736960/2022-06-26_19-31-40.mp4

**Comment by FoxMcloud5655** [comment]
Alright, I think I know what's happening.  Due to how your system is laid out, the first Fusion Crafting Core is picking up the Crafting Injectors from the far end of the second Fusion Crafting Core that are facing the first Fusion Crafting Core (and would be valid if the other injectors weren't in the way).

Try this setup on a different Y level, either +2 or -2 and tell me if it still misbehaves.

**Comment by brandon3055** [comment]
This is now fixed.

**Comment by SeeTwoDev** [comment]
SOrry to resurect this post but this is still an issue on Draconic-Evolution-1.18.2-3.0.29.524-universal.jar (Currently in SkyT 0.7.2)

Moving the 2nd setup did fix the issue

**Comment by FoxMcloud5655** [comment]
You're sure it was doing the same thing?  Can you post a video of this issue still happening (if you do, please also mouse over your chest armor at least once)?  If it truly is, I'll reopen this issue.
